// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Keys          map[int32]string       `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Types         map[int32]string       `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values        map[int32][]byte       `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetKeys() map[int32]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Request) GetTypes() map[int32]string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Request) GetValues() map[int32][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Consume       int32                  `protobuf:"varint,2,opt,name=consume,proto3" json:"consume,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ReplyData             `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetConsume() int32 {
	if x != nil {
		return x.Consume
	}
	return 0
}

func (x *Reply) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Reply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Reply) GetData() *ReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          map[int32]string       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Types         map[int32]string       `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values        map[int32][]byte       `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyData) Reset() {
	*x = ReplyData{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyData) ProtoMessage() {}

func (x *ReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyData.ProtoReflect.Descriptor instead.
func (*ReplyData) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyData) GetKeys() map[int32]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ReplyData) GetTypes() map[int32]string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ReplyData) GetValues() map[int32][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x06nyxrpc\"\xe5\x02\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12-\n" +
	"\x04keys\x18\x02 \x03(\v2\x19.nyxrpc.Request.KeysEntryR\x04keys\x120\n" +
	"\x05types\x18\x03 \x03(\v2\x1a.nyxrpc.Request.TypesEntryR\x05types\x123\n" +
	"\x06values\x18\x04 \x03(\v2\x1b.nyxrpc.Request.ValuesEntryR\x06values\x1a7\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x82\x01\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\aconsume\x18\x02 \x01(\x05R\aconsume\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12%\n" +
	"\x04data\x18\x05 \x01(\v2\x11.nyxrpc.ReplyDataR\x04data\"\xd5\x02\n" +
	"\tReplyData\x12/\n" +
	"\x04keys\x18\x01 \x03(\v2\x1b.nyxrpc.ReplyData.KeysEntryR\x04keys\x122\n" +
	"\x05types\x18\x02 \x03(\v2\x1c.nyxrpc.ReplyData.TypesEntryR\x05types\x125\n" +
	"\x06values\x18\x03 \x03(\v2\x1d.nyxrpc.ReplyData.ValuesEntryR\x06values\x1a7\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012d\n" +
	"\x06NYXRpc\x12(\n" +
	"\x04Call\x12\x0f.nyxrpc.Request\x1a\r.nyxrpc.Reply\"\x00\x120\n" +
	"\n" +
	"CallStream\x12\x0f.nyxrpc.Request\x1a\r.nyxrpc.Reply\"\x000\x01B\aZ\x05../pbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_proto_goTypes = []any{
	(*Request)(nil),   // 0: nyxrpc.Request
	(*Reply)(nil),     // 1: nyxrpc.Reply
	(*ReplyData)(nil), // 2: nyxrpc.ReplyData
	nil,               // 3: nyxrpc.Request.KeysEntry
	nil,               // 4: nyxrpc.Request.TypesEntry
	nil,               // 5: nyxrpc.Request.ValuesEntry
	nil,               // 6: nyxrpc.ReplyData.KeysEntry
	nil,               // 7: nyxrpc.ReplyData.TypesEntry
	nil,               // 8: nyxrpc.ReplyData.ValuesEntry
}
var file_rpc_proto_depIdxs = []int32{
	3, // 0: nyxrpc.Request.keys:type_name -> nyxrpc.Request.KeysEntry
	4, // 1: nyxrpc.Request.types:type_name -> nyxrpc.Request.TypesEntry
	5, // 2: nyxrpc.Request.values:type_name -> nyxrpc.Request.ValuesEntry
	2, // 3: nyxrpc.Reply.data:type_name -> nyxrpc.ReplyData
	6, // 4: nyxrpc.ReplyData.keys:type_name -> nyxrpc.ReplyData.KeysEntry
	7, // 5: nyxrpc.ReplyData.types:type_name -> nyxrpc.ReplyData.TypesEntry
	8, // 6: nyxrpc.ReplyData.values:type_name -> nyxrpc.ReplyData.ValuesEntry
	0, // 7: nyxrpc.NYXRpc.Call:input_type -> nyxrpc.Request
	0, // 8: nyxrpc.NYXRpc.CallStream:input_type -> nyxrpc.Request
	1, // 9: nyxrpc.NYXRpc.Call:output_type -> nyxrpc.Reply
	1, // 10: nyxrpc.NYXRpc.CallStream:output_type -> nyxrpc.Reply
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
