// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_NIL        Type = 0
	Type_INT        Type = 1
	Type_INT8       Type = 2
	Type_INT16      Type = 3
	Type_INT32      Type = 4
	Type_INT64      Type = 5
	Type_UINT       Type = 6
	Type_UINT8      Type = 7
	Type_UINT16     Type = 8
	Type_UINT32     Type = 9
	Type_UINT64     Type = 10
	Type_FLOAT32    Type = 11
	Type_FLOAT64    Type = 12
	Type_BOOL       Type = 13
	Type_STRING     Type = 14
	Type_BYTES      Type = 15
	Type_COMPLEX64  Type = 16
	Type_COMPLEX128 Type = 17
	Type_TIME       Type = 18
	Type_OBJECT     Type = 19
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "NIL",
		1:  "INT",
		2:  "INT8",
		3:  "INT16",
		4:  "INT32",
		5:  "INT64",
		6:  "UINT",
		7:  "UINT8",
		8:  "UINT16",
		9:  "UINT32",
		10: "UINT64",
		11: "FLOAT32",
		12: "FLOAT64",
		13: "BOOL",
		14: "STRING",
		15: "BYTES",
		16: "COMPLEX64",
		17: "COMPLEX128",
		18: "TIME",
		19: "OBJECT",
	}
	Type_value = map[string]int32{
		"NIL":        0,
		"INT":        1,
		"INT8":       2,
		"INT16":      3,
		"INT32":      4,
		"INT64":      5,
		"UINT":       6,
		"UINT8":      7,
		"UINT16":     8,
		"UINT32":     9,
		"UINT64":     10,
		"FLOAT32":    11,
		"FLOAT64":    12,
		"BOOL":       13,
		"STRING":     14,
		"BYTES":      15,
		"COMPLEX64":  16,
		"COMPLEX128": 17,
		"TIME":       18,
		"OBJECT":     19,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Data          []*Field               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetData() []*Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Consume       int32                  `protobuf:"varint,2,opt,name=consume,proto3" json:"consume,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*Field               `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetConsume() int32 {
	if x != nil {
		return x.Consume
	}
	return 0
}

func (x *Reply) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Reply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Reply) GetData() []*Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=nyxrpc.Type" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_NIL
}

func (x *Field) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x06nyxrpc\"D\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.nyxrpc.FieldR\x04data\"~\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\aconsume\x18\x02 \x01(\x05R\aconsume\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12!\n" +
	"\x04data\x18\x05 \x03(\v2\r.nyxrpc.FieldR\x04data\"S\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\x04type\x18\x02 \x01(\x0e2\f.nyxrpc.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value*\xec\x01\n" +
	"\x04Type\x12\a\n" +
	"\x03NIL\x10\x00\x12\a\n" +
	"\x03INT\x10\x01\x12\b\n" +
	"\x04INT8\x10\x02\x12\t\n" +
	"\x05INT16\x10\x03\x12\t\n" +
	"\x05INT32\x10\x04\x12\t\n" +
	"\x05INT64\x10\x05\x12\b\n" +
	"\x04UINT\x10\x06\x12\t\n" +
	"\x05UINT8\x10\a\x12\n" +
	"\n" +
	"\x06UINT16\x10\b\x12\n" +
	"\n" +
	"\x06UINT32\x10\t\x12\n" +
	"\n" +
	"\x06UINT64\x10\n" +
	"\x12\v\n" +
	"\aFLOAT32\x10\v\x12\v\n" +
	"\aFLOAT64\x10\f\x12\b\n" +
	"\x04BOOL\x10\r\x12\n" +
	"\n" +
	"\x06STRING\x10\x0e\x12\t\n" +
	"\x05BYTES\x10\x0f\x12\r\n" +
	"\tCOMPLEX64\x10\x10\x12\x0e\n" +
	"\n" +
	"COMPLEX128\x10\x11\x12\b\n" +
	"\x04TIME\x10\x12\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x132d\n" +
	"\x06NYXRpc\x12(\n" +
	"\x04Call\x12\x0f.nyxrpc.Request\x1a\r.nyxrpc.Reply\"\x00\x120\n" +
	"\n" +
	"CallStream\x12\x0f.nyxrpc.Request\x1a\r.nyxrpc.Reply\"\x000\x01B\aZ\x05../pbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_proto_goTypes = []any{
	(Type)(0),       // 0: nyxrpc.Type
	(*Request)(nil), // 1: nyxrpc.Request
	(*Reply)(nil),   // 2: nyxrpc.Reply
	(*Field)(nil),   // 3: nyxrpc.Field
}
var file_rpc_proto_depIdxs = []int32{
	3, // 0: nyxrpc.Request.data:type_name -> nyxrpc.Field
	3, // 1: nyxrpc.Reply.data:type_name -> nyxrpc.Field
	0, // 2: nyxrpc.Field.type:type_name -> nyxrpc.Type
	1, // 3: nyxrpc.NYXRpc.Call:input_type -> nyxrpc.Request
	1, // 4: nyxrpc.NYXRpc.CallStream:input_type -> nyxrpc.Request
	2, // 5: nyxrpc.NYXRpc.Call:output_type -> nyxrpc.Reply
	2, // 6: nyxrpc.NYXRpc.CallStream:output_type -> nyxrpc.Reply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
