// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: rpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NYXRpc_Call_FullMethodName       = "/nyxrpc.NYXRpc/Call"
	NYXRpc_CallStream_FullMethodName = "/nyxrpc.NYXRpc/CallStream"
)

// NYXRpcClient is the client API for NYXRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NYXRpcClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	CallStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error)
}

type nYXRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNYXRpcClient(cc grpc.ClientConnInterface) NYXRpcClient {
	return &nYXRpcClient{cc}
}

func (c *nYXRpcClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, NYXRpc_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nYXRpcClient) CallStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NYXRpc_ServiceDesc.Streams[0], NYXRpc_CallStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Reply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NYXRpc_CallStreamClient = grpc.ServerStreamingClient[Reply]

// NYXRpcServer is the server API for NYXRpc service.
// All implementations must embed UnimplementedNYXRpcServer
// for forward compatibility.
type NYXRpcServer interface {
	Call(context.Context, *Request) (*Reply, error)
	CallStream(*Request, grpc.ServerStreamingServer[Reply]) error
	mustEmbedUnimplementedNYXRpcServer()
}

// UnimplementedNYXRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNYXRpcServer struct{}

func (UnimplementedNYXRpcServer) Call(context.Context, *Request) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedNYXRpcServer) CallStream(*Request, grpc.ServerStreamingServer[Reply]) error {
	return status.Error(codes.Unimplemented, "method CallStream not implemented")
}
func (UnimplementedNYXRpcServer) mustEmbedUnimplementedNYXRpcServer() {}
func (UnimplementedNYXRpcServer) testEmbeddedByValue()                {}

// UnsafeNYXRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NYXRpcServer will
// result in compilation errors.
type UnsafeNYXRpcServer interface {
	mustEmbedUnimplementedNYXRpcServer()
}

func RegisterNYXRpcServer(s grpc.ServiceRegistrar, srv NYXRpcServer) {
	// If the following call panics, it indicates UnimplementedNYXRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NYXRpc_ServiceDesc, srv)
}

func _NYXRpc_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NYXRpcServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NYXRpc_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NYXRpcServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NYXRpc_CallStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NYXRpcServer).CallStream(m, &grpc.GenericServerStream[Request, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NYXRpc_CallStreamServer = grpc.ServerStreamingServer[Reply]

// NYXRpc_ServiceDesc is the grpc.ServiceDesc for NYXRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NYXRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nyxrpc.NYXRpc",
	HandlerType: (*NYXRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _NYXRpc_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallStream",
			Handler:       _NYXRpc_CallStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
